services:
  loci-db:
    container_name: loci-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: loci
    volumes:
      - loci-db:/data/postgres

    ports:
      - 5432:5432
    networks:
      - loci-net

  loci-pgadmin:
    container_name: loci-pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - loci-net




  loci-keycloak:
    container_name: loci-keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - loci-net
    depends_on:
      - loci-db
    volumes:
      - ./apps/keycloak/import:/opt/keycloak/data/import
      - loci-keycloak:/opt/keycloak/data
    command:
      start-dev --import-realm


networks:
  loci-net:
    driver: bridge
volumes:
  loci-db:
    driver: local
  loci-keycloak:
    driver: local
